#ifndef _MUSIC_H
#define _MUSIC_H

#define _01CYBERPUNK_THEME_ 0
#define _02CYBERPUNK_AMBIENT_ 1
#define _03CYBERPUNK_AMBIENT_ 2
#define _05CYBERPUNK_DARKSIDE_ 3
#define _06CYBERPUNK_INTHECLUB_ 4
#define _08CYBERPUNK_LOVETHEME_ 5
#define _09CYBERPUNK_AMBIENT_ 6
#define _10CYBERPUNK_LOSTSOULS_ 7

#endif

